name: biobb_wf_protein-complex_md_setup
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - biobb_io==4.2.0
  - biobb_model==4.2.0
  - biobb_common==4.2.0
  # Old config interrupted by the GROMACS issue
  # See: https://github.com/bioexcel/biobb_gromacs/issues/23
  - mamba
  - cmake
  - libhwloc
  - ocl-icd
  - biopython
  #- fftw #Not needed if using CUDA cufft
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - cython
  - h5py
  - pandas
  - openbabel
  - propka 
  - pdb2pqr 
  - rdkit 
  - acpype
  - tzdata
  - os_command_py
  - pdb_manip_py
  - ambertools         
  - arpack
  - brotli
  - brotli-bin
  - chardet
  - contourpy
  - cycler
  - fonttools
  - freetype-py
  - greenlet
  - hdf4
  - joblib
  - kiwisolver
  - lcms2
  - lerc
  - libboost
  - libboost-python
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libdeflate
  - libhwloc
  - libnetcdf
  - libstdcxx
  - libtiff
  - libwebp-base
  - libzip
  - munkres
  - netcdf-fortran
  - ocl-icd
  - openjpeg
  - parmed
  - pdb2pqr_htmd_propka30
  - perl
  - pillow
  - platformdirs
  - pycairo
  - pyparsing
  - python-tzdata
  - qhull
  - reportlab
  - rlpycairo
  - sqlalchemy
  - unicodedata2
  - xorg-libxt
  # Resume old config
  - biobb_chemistry==4.2.0
  - biobb_structure_utils==4.2.0
  - jupyter
  - plotly
  - nglview
  - simpletraj
  - pip:
    # Install python bindings only. Will compile GROMACS manually
    - mmcif-pdbx
    - biobb_analysis==4.2.0
    - biobb_gromacs==4.2.0
    - gromacs_py
